#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.6.1
clone: 
 depth: full

pipelines: 
 branches: 
   main:
     - step: 
         name: Build and Deploy Snapshot Artifact 
         trigger: automatic
         image: maven:3
         caches:  
         - maven # cache the maven 
         script: 
         - mvn install clean 
         - mvn package
 
     - step: 
         name: Create artifact in HEROKU - Prod 
         deployment: production 
         script: 
         - HEROKU_API_KEY=$HEROKU_API_KEY mvn heroku:deploy